DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS study_groups CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS coordinates CASCADE;
DROP TABLE IF EXISTS semesters CASCADE;
DROP TABLE IF EXISTS colors CASCADE;

DROP SEQUENCE IF EXISTS users_id_seq;
DROP SEQUENCE IF EXISTS study_groups_id_seq;
DROP SEQUENCE IF EXISTS admin_id_seq;
DROP SEQUENCE IF EXISTS coord_id_seq;
DROP SEQUENCE IF EXISTS semester_id_seq;
DROP SEQUENCE IF EXISTS color_id_seq;

DROP INDEX IF EXISTS idx_study_groups_name;
DROP INDEX IF EXISTS idx_study_groups_owner;
DROP INDEX IF EXISTS idx_users_login;